#!/bin/bash
base=$(basename $1)
filename=${base%.*}
redis=$(redis-cli ping 2> /dev/null)

if [[ $redis == 'PONG' ]]; then
    python -m test.$filename
else
    echo 'Please run redis-server before running these tests.'
fi
