#!/usr/bin/env python
import os
import argparse
from src import app, roster, account

if __name__ == '__main__':
    print 'Starting...'
    parser = argparse.ArgumentParser(
            description='Run deamons for git infrastructure.')
    parser.add_argument('--roster',
            dest='roster',
            required=False,
            help='Roster file to parse.')
    parser.add_argument('--account-init',
            dest='account_init',
            required=False,
            action='store_true',
            help='Initialize accounts in database')
    parser.add_argument('--test-init',
            dest='test_init',
            required=False,
            action='store_true',
            help='Initialize accounts in database without real account forms.')
    parser.add_argument('--min-login-len',
            type=int,
            dest='min_len',
            required=False,
            default=2,
            help='Minimum length of student logins. (i.e. "aa" = 2, "aaa" = 3)')

    args = parser.parse_args()

    if args.roster:
        roster_file = args.roster[0]
        print 'Enrolling from roster file: {0}'.format(roster_file)
        roster.parse_enroll(roster_file)

    if args.test_init:
        print 'Registering 1000 dummy accounts.'
        account.register_num_accounts(1000)

    if args.account_init:
        print 'Registering all accounts in account-forms/'
        account.register_logins()

    app.run(no_account_forms=args.test_init)
